#!/usr/bin/env python

import sys
sys.path.append('..')

from isochrones.summary import make_summary_df

import argparse

parser = argparse.ArgumentParser()

parser.add_argument('directory')
parser.add_argument('--processes', '-p', default=1, type=int)

args = parser.parse_args()

make_summary_df(args.directory, processes=args.processes)

