#!/usr/bin/env python

import sys
import pandas as pd
import numpy as np
import cPickle as pickle
from scipy.interpolate import LinearNDInterpolator as interpnd

from isochrones.config import ISOCHRONES

DATADIR = os.path.join(ISOCHRONES, 'dartmouth')

df = pd.read_hdf(os.path.join(DATADIR,'SDSSugriz.h5'))
N = len(df)
pts = np.zeros((N,3))
pts[:,0] = np.array(df['MMo'])
pts[:,1] = np.log10(np.array(df['age'])*1e9)
pts[:,2] = np.array(df['feh'])
gmags = np.array(df['sdss_g'])

gfn = interpnd(pts,gmags)

f = open(os.path.join(DATADIR,'dartmouth.tri'),'wb')
pickle.dump(gfn.tri,f)
f.close()
